language: scala

scala:
   - 2.10.5
   - 2.11.7

before_install:
   # prevent OutOfMemoryError: unable to create new native thread
   - ulimit -t 166384
   # get the actually set values
   - ulimit -a

cache:
  directories:
    - $HOME/.ivy2

# use container 
sudo: false
