language: scala

scala:
   - 2.11.8
   - 2.12.1

jdk:
   - oraclejdk8

before_install:
   # prevent OutOfMemoryError: unable to create new native thread
   - ulimit -t 166384
   # get the actually set values
   - ulimit -a

cache:
  directories:
    - $HOME/.ivy2

# use container 
sudo: false
